# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53f19dfcdbbf4b43e3ee15ebd600494450cdbeaf8e4b33d15e1bde169eb64f5df0088e65c73f93994a43686597b1b8700be735d4d0f2ded69c8cd4d81e15e6af

test:
  secret_key_base: 6c9f535405d6183901c0a327019928a14d673d78f733e2710923af5ef66d9cb6d16369578ff6af0c9a8259b95b49ab60e9d5ed802d89b74b5cec4bd17a321a8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
